command: [
  "python",
  "app_dash.py"
]

env:
  - name: "SERVING_ENDPOINT"
    valueFrom: "serving-endpoint"
  - name: "ZEROBUS_SERVER_ENDPOINT"
    value: "<ZEROBUS_SERVER_ENDPOINT>"
  - name: "ZEROBUS_TABLE"
    value: "<ZEROBUS_TABLE>"
  - name: "ZEROBUS_HOST"
    value: "<ZEROBUS_HOST>"
  - name: "DATABRICKS_CLIENT_ID"
    value: "<DATABRICKS_CLIENT_ID>"
  - name: "DATABRICKS_CLIENT_SECRET"
    value: "<DATABRICKS_CLIENT_SECRET>"
